var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5bc28079._.js")
R.c("server/chunks/ssr/Desktop_elektronova-recovered_ed1bdf5c._.js")
R.c("server/chunks/ssr/33d1b_next_dist_10d6f325._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8624da05._.js")
R.c("server/chunks/ssr/[root-of-the-server]__879bd8b1._.js")
R.c("server/chunks/ssr/33d1b_next_dist_75d089fc._.js")
R.c("server/chunks/ssr/Desktop_elektronova-recovered_src_app_82436c09._.js")
R.c("server/chunks/ssr/33d1b_920880ec._.js")
R.c("server/chunks/ssr/33d1b_next_dist_client_components_a62430d2._.js")
R.c("server/chunks/ssr/33d1b_next_dist_client_components_builtin_forbidden_5e59ba00.js")
R.c("server/chunks/ssr/3d860_elektronova-recovered__next-internal_server_app__not-found_page_actions_d16012bb.js")
R.m(93490)
module.exports=R.m(93490).exports
