#!/bin/bash
echo "============================================"
echo "  ELEKTRONOVA - Autodeploy Setup"
echo "============================================"
echo ""
echo "Kjo skriptë krijon SSH key për GitHub Actions"
echo ""

ssh-keygen -t ed25519 -f /tmp/elektronova_deploy_key -N "" -q
echo ""
echo "============================================"
echo "  HAPI 1: Shto këtë PUBLIC key në server"
echo "============================================"
echo ""
echo "Ekzekuto këtë komandë në VPS:"
echo ""
echo "echo '$(cat /tmp/elektronova_deploy_key.pub)' >> ~/.ssh/authorized_keys"
echo ""
echo "============================================"
echo "  HAPI 2: Shto këto 3 Secrets në GitHub"
echo "============================================"
echo ""
echo "Shko: https://github.com/wrotexx1237/elektronova-asset-manager/settings/secrets/actions"
echo ""
echo "1. SERVER_IP = IP e VPS-it tënd"
echo "2. SERVER_USER = root (ose username tjetër)"
echo "3. SSH_PRIVATE_KEY = kopjo tekstin më poshtë:"
echo ""
echo "------- KOPJO NGA KETU -------"
cat /tmp/elektronova_deploy_key
echo "------- DERI KETU -------"
echo ""
rm -f /tmp/elektronova_deploy_key /tmp/elektronova_deploy_key.pub
echo "============================================"
echo "  Tani çdo push në main bën autodeploy!"
echo "============================================"
