// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/about" | "/[locale]/blog" | "/[locale]/blog/[slug]" | "/[locale]/contact" | "/[locale]/cookie-policy" | "/[locale]/faq" | "/[locale]/locations/[slug]" | "/[locale]/portfolio" | "/[locale]/privacy-policy" | "/[locale]/services" | "/[locale]/services/[slug]" | "/[locale]/terms-of-service" | "/shtojegooglen"
type AppRouteHandlerRoutes = "/sitemap-blog.xml" | "/sitemap-locations.xml" | "/sitemap-main.xml" | "/sitemap-services.xml" | "/sitemap.xml"
type PageRoutes = never
type LayoutRoutes = "/[locale]" | "/shtojegooglen"
type RedirectRoutes = "/blogu" | "/blogu/[slug]" | "/elektricist-[id]" | "/en/blog/energjia-solare-elektrike" | "/en/blog/rendesia-e-alarmit-wireless" | "/en/elektricist-[id]" | "/en/rreth-nesh" | "/en/services/sistemet-nvr-dvr" | "/portofolio" | "/rreth-nesh" | "/sherbimet" | "/sq/about" | "/sq/blogu/5-common-security-camera-mistakes" | "/sq/blogu/security-camera-installation-cost-kosovo" | "/sq/locations/[slug]" | "/sq/services/[slug]" | "/sq/services/instalim-ndricimi"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/blog": { "locale": string; }
  "/[locale]/blog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/cookie-policy": { "locale": string; }
  "/[locale]/faq": { "locale": string; }
  "/[locale]/locations/[slug]": { "locale": string; "slug": string; }
  "/[locale]/portfolio": { "locale": string; }
  "/[locale]/privacy-policy": { "locale": string; }
  "/[locale]/services": { "locale": string; }
  "/[locale]/services/[slug]": { "locale": string; "slug": string; }
  "/[locale]/terms-of-service": { "locale": string; }
  "/blogu": {}
  "/blogu/[slug]": { "slug": string; }
  "/elektricist-[id]": {}
  "/en/blog/energjia-solare-elektrike": {}
  "/en/blog/rendesia-e-alarmit-wireless": {}
  "/en/elektricist-[id]": {}
  "/en/rreth-nesh": {}
  "/en/services/sistemet-nvr-dvr": {}
  "/portofolio": {}
  "/rreth-nesh": {}
  "/sherbimet": {}
  "/shtojegooglen": {}
  "/sitemap-blog.xml": {}
  "/sitemap-locations.xml": {}
  "/sitemap-main.xml": {}
  "/sitemap-services.xml": {}
  "/sitemap.xml": {}
  "/sq/about": {}
  "/sq/blogu/5-common-security-camera-mistakes": {}
  "/sq/blogu/security-camera-installation-cost-kosovo": {}
  "/sq/locations/[slug]": { "slug": string; }
  "/sq/services/[slug]": { "slug": string; }
  "/sq/services/instalim-ndricimi": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
  "/shtojegooglen": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
