// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cookie-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cookie-policy">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cookie-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/faq">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/locations/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/locations/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/locations/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/portfolio">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy-policy">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/services/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/services/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/services/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/services">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/terms-of-service">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shtojegooglen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shtojegooglen">> = Specific
  const handler = {} as typeof import("../../src/app/shtojegooglen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemap-blog.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap-blog.xml">> = Specific
  const handler = {} as typeof import("../../src/app/sitemap-blog.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemap-locations.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap-locations.xml">> = Specific
  const handler = {} as typeof import("../../src/app/sitemap-locations.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemap-main.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap-main.xml">> = Specific
  const handler = {} as typeof import("../../src/app/sitemap-main.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemap-services.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap-services.xml">> = Specific
  const handler = {} as typeof import("../../src/app/sitemap-services.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemap.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap.xml">> = Specific
  const handler = {} as typeof import("../../src/app/sitemap.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/shtojegooglen/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/shtojegooglen">> = Specific
  const handler = {} as typeof import("../../src/app/shtojegooglen/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
