CREATE TABLE "workers" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"personal_number" text NOT NULL,
	"address" text NOT NULL,
	"city" text NOT NULL,
	"phone" text NOT NULL,
	"email" text,
	"profession" text NOT NULL,
	"position" text NOT NULL,
	"department" text NOT NULL,
	"salary" real NOT NULL,
	"bank_account" text NOT NULL,
	"bank_name" text NOT NULL,
	"start_date" text NOT NULL,
	"contract_type" text DEFAULT 'Caktuar' NOT NULL,
	"contract_duration" text,
	"working_hours" integer DEFAULT 40 NOT NULL,
	"work_schedule" text DEFAULT 'Hëne - Premte, 08:00 - 16:00' NOT NULL,
	"workplace" text DEFAULT 'Zyrat qendrore / Terren' NOT NULL,
	"probation_period" text DEFAULT '1 Muaj' NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
