var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/shtojegooglen/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2da14af8._.js")
R.c("server/chunks/ssr/Desktop_elektronova-recovered_ed1bdf5c._.js")
R.c("server/chunks/ssr/Desktop_elektronova-recovered_40cd2343._.js")
R.c("server/chunks/ssr/[root-of-the-server]__21a3708d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__879bd8b1._.js")
R.c("server/chunks/ssr/33d1b_next_dist_75d089fc._.js")
R.c("server/chunks/ssr/Desktop_elektronova-recovered_src_app_82436c09._.js")
R.c("server/chunks/ssr/33d1b_next_dist_client_components_builtin_global-error_fb04f1cf.js")
R.c("server/chunks/ssr/33d1b_next_dist_client_components_a62430d2._.js")
R.c("server/chunks/ssr/33d1b_next_dist_client_components_builtin_forbidden_5e59ba00.js")
R.c("server/chunks/ssr/33d1b_next_dist_client_components_builtin_unauthorized_fdb92af9.js")
R.c("server/chunks/ssr/Desktop_elektronova-recovered_src_app_shtojegooglen_layout_tsx_e84bca25._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8671a188._.js")
R.m(35833)
module.exports=R.m(35833).exports
