'use server';

import { Resend } from 'resend';

export async function sendLeadEmail(formData: {
  name: string;
  phone: string;
  email: string;
  city: string;
  service: string;
  message: string;
}) {
  console.log('API Key present:', !!process.env.RESEND_API_KEY);
  const resend = new Resend(process.env.RESEND_API_KEY);
  try {
    const { name, phone, email, city, service, message } = formData;

    const { data, error } = await resend.emails.send({
      from: 'ElektroNova Website <onboarding@resend.dev>',
      to: ['endritsmajlib@gmail.com'],
      subject: `New Lead: ${name} - ${service}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
          <h2 style="color: #0070f3; border-bottom: 2px solid #0070f3; padding-bottom: 10px;">New Inquiry from ElektroNova</h2>
          <p><strong>Customer Name:</strong> ${name}</p>
          <p><strong>Phone Number:</strong> ${phone}</p>
          <p><strong>Email Address:</strong> ${email}</p>
          <p><strong>City:</strong> ${city}</p>
          <p><strong>Interested Service:</strong> ${service}</p>
          <div style="background: #f9f9f9; padding: 15px; border-radius: 5px; margin-top: 20px;">
            <p><strong>Message:</strong></p>
            <p>${message.replace(/\n/g, '<br>')}</p>
          </div>
          <footer style="margin-top: 30px; font-size: 12px; color: #888;">
            This email was automatically generated by the ElektroNova website contact form.
          </footer>
        </div>
      `,
    });

    if (error) {
      console.error('Resend Error:', error);
      return { success: false, error: error.message };
    }

    return { success: true, data };
  } catch (err: any) {
    console.error('Server Action Error:', err);
    return { success: false, error: err.message || 'Internal server error' };
  }
}
